# Generated by Django 4.1.4 on 2023-03-23 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_friendship_unique_friendship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="follower_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
