# Generated by Django 4.1.4 on 2023-03-24 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_friendship_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendship",
            old_name="data_created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="friendship",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("follower", "following"), name="unique_friendship"),
        ),
    ]
