# Generated by Django 4.1.4 on 2023-03-24 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_data_created_friendship_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
